name: Continuous integration

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup
        uses: './.github/actions/ci-setup'
        with:
          python-version: '3.10'
      #----------------------------------------------
      #       Run tests
      #----------------------------------------------
      - name: Test with pytest
        run: |
          poetry run python -m pytest -s
  Audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup
        uses: './.github/actions/ci-setup'
        with:
          python-version: '3.10'
      #----------------------------------------------
      #       Run tests
      #----------------------------------------------
      - name: Audit packages
        run: |
          poetry run safety check
